server:
  port: 4000

spring:
  application:
    name: botvinnikAPI

botvinnik:
  providers:
    - name: local-ollama
      type: ollama
      base-url: http://localhost:11434
    - name: google
      type: gemini
      api-key: ${GEMINI_API_KEY}